baseurl      = "https://yordan.llc"
title        = "A blog from code space"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Brought to you by Fernando Yordan LLC"

  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"


[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
