baseurl      = "https://yordan.llc"
title        = "A blog from code space"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Brought to you by Fernando Yordan LLC"

  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "A homepage, blog, and portfolio for Fernando Yordan LLC, a company for software development and fractional cto services."
  keywords = "homepage, blog, cto, software, devops, ai, developer, engineer"
  images = [""]

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"


[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Services"
url = "/services"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[[menu.main]]
name = "Privacy"
url = "/privacy"
weight = 4

[[menu.main]]
name = "Terms"
url = "/toc"
weight = 5
